set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RiuCadNavigation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuCursors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuDragDrop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuFemResultTextBuilder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuGeoQuestNavigation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuInterfaceToViewWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPlotCurveSymbol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPlotCurveSymbolImageCreator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtSymbol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPlotCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtPlotCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtPlotCurveDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtPlotItem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPlotMainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMainWindowBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMdiArea.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMdiSubWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuProcessMonitor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuProjectPropertyView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPropertyViewTabWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPropertyViewWizard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPvtPlotPanel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPvtPlotUpdater.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPvtPlotWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPlotUpdater.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtLinearScaleEngine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtScalePicker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtCurvePointTracker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtPlotWheelZoomer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuWidgetDragger.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuRecentFileActionProvider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuRelativePermeabilityPlotPanel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuRelativePermeabilityPlotUpdater.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuResultInfoPanel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuResultQwtPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuResultTextBuilder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuRmsNavigation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSelectionChangedHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Riu3dSelectionManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSimpleHistogramWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuDockedQwtPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuGridCrossQwtPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSummaryQwtPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSummaryPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuTextDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuTimeStepChangedHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuTofAccumulatedPhaseFractionsPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuToolTipMenu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuTreeViewEventFilter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuViewer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuViewerCommands.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuCellAndNncPickEventHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPickItemInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuWellLogTrack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuWellLogPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSummaryMultiPlotPage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSummaryMultiPlotBook.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMultiPlotPage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMultiPlotBook.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPlotWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPlotAxis.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtPlotWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtPlotLegend.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPlotAnnotationTool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuGeoMechXfTensorResultAccessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuFemTimeHistoryResultAccessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuEditPerforationCollectionWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuAdvancedSnapshotExportWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuWellAllocationPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuFlowCharacteristicsPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuNightchartsWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMessagePanel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMessageDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPlotObjectPicker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuContextMenuLauncher.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSummaryVectorSelectionUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSummaryVectorSelectionDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSummaryVectorSelectionWidgetCreator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSummaryQuantityNameInfoProvider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuExpressionContextMenuManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuCalculationsContextMenuManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuGridStatisticsHistogramWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMohrsCirclePlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuPlotMainWindowTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Riu3DMainWindowTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuDockWidgetTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtCurveSelectorFilter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtPlotItemGroup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtPlotTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuDepthQwtPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuWellPathComponentPlotItem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuDraggableOverlayFrame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMdiMaximizeWindowGuard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMainWindowTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuComparisonViewMover.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuAbstractOverlayContentFrame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuAbstractLegendFrame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuCategoryLegendFrame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuScalarMapperLegendFrame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuFileDialogTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuGuiTheme.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuSeismicHistogramPanel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQssSyntaxHighlighter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuTextEditWithCompletion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuTextContentFrame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtLegendOverlayContentFrame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtDateScaleWrapper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMatrixPlotWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMenuBarBuildTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtPlotRectAnnotation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuQwtPlotZoomerMultiAxes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuCellSelectionTool.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
