-- This reservoir simulation deck is made available under the Open Database
-- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
-- individual contents of the database are licensed under the Database Contents
-- License: http://opendatacommons.org/licenses/dbcl/1.0/

-- Copyright (C) 2018 Equinor

-- This file is one of the include files for BASE_MODEL_1.DATA.

-- ----------------------------------------------------------------------------
-- ----------------------------------------------------------------------------

EQLNUM 
   1    1    1    1    1    1    1    1    1    1    1    1 
   1    1    1    1    1    1    1    1    1    1    1    1 
   2    2    2    2    2    2    2    2    2    2    2    2 
   2    2    2    2    2    2    2    2    2    2    2    2 
   1    1    1    1    1    1    1    1    1    1    1    1 
   1    1    1    1    1    1    1    1    1    1    1    1 
   2    2    2    2    2    2    2    2    2    2    2    2 
   2    2    2    2    2    2    2    2    2    2    2    2 
   1    1    1    1    1    1    1    1    1    1    1    1 
   1    1    1    1    1    1    1    1    1    1    1    1 
   2    2    2    2    2    2    2    2    2    2    2    2 
   2    2    2    2    2    2    2    2    2    2    2    2 
   1    1    1    1    1    1    1    1    1    1    1    1 
   1    1    1    1    1    1    1    1    1    1    1    1 
   2    2    2    2    2    2    2    2    2    2    2    2 
   2    2    2    2    2    2    2    2    2    2    2    2 
   3    3    3    3    3    3    3    3    3    3    3    3 
   3    3    3    3    3    3    3    3    3    3    3    3 
   4    4    4    4    4    4    4    4    4    4    4    4 
   4    4    4    4    4    4    4    4    4    4    4    4 
   3    3    3    3    3    3    3    3    3    3    3    3 
   3    3    3    3    3    3    3    3    3    3    3    3 
   4    4    4    4    4    4    4    4    4    4    4    4 
   4    4    4    4    4    4    4    4    4    4    4    4 
   3    3    3    3    3    3    3    3    3    3    3    3 
   3    3    3    3    3    3    3    3    3    3    3    3 
   4    4    4    4    4    4    4    4    4    4    4    4 
   4    4    4    4    4    4    4    4    4    4    4    4 
/ 
