set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RiaArgumentParser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaDateStringParser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaColorTables.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaColorTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaEclipseUnitTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaImageCompareReporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaImageFileCompare.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaImageTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaLogging.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaProjectModifier.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaRegressionTest.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaImportEclipseCaseTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaQDateTimeTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaWellNameComparer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaStdStringTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaInterpolationTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaSimWellBranchTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaProjectFileTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaStringEncodingTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaTextStringTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaTextFileCompare.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaRegressionTestRunner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaExtractionTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaFilePathTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaFileSearchTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaCurveMerger.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaCurveDataTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaWellLogCurveMerger.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaTimeHistoryCurveResampler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaWeightedGeometricMeanCalculator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaWeightedHarmonicMeanCalculator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaNameUniquenessTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaOptionItemFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaGitDiff.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaWslTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaHpcTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaCellDividingTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaFieldHandleTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaBoundingBoxTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaTimeTTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaValidRegExpValidator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaEnsembleNameTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaVec3Tools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaNetworkTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaOpenMPTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaNumericalTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPhaseTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaRegressionTextTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaFileLogger.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaProjectBackupTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaQuantityInfoTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaAngleUtils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaToCafLogging.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaToCvfLogging.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaZScaleTools.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
