set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimVfpDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCustomVfpPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimVfpPlotCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimVfpTableData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimVfpTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimVfpDataCollection.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
