set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RiaApplication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaConsoleApplication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaGuiApplication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaCompletionTypeCalculationScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaFractureDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPreferences.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPreferencesSummary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPreferencesGeoMech.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPreferencesGrid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPreferencesSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaExperimentalFeatures.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPreferencesOsdu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPreferencesOpm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPreferencesSumo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPorosityModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaCurveSetDefinition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaRftPltCurveDefinition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaViewRedrawScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPlotWindowRedrawScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaMemoryCleanup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaFontCache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaEclipseFileNameTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaFeatureCommandContext.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaStringListSerializer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaStringPool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaNncDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPlotDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaStimPlanModelDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaThermalFractureDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaResultNames.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaRftDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaDateTimeDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaPlotCollectionScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaSeismicDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaLasDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaOsduDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaCloudDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaWellFlowDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaWellLogTrackDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaQuickAccessScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaGridDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaModelExportDefines.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
