set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicNewAnalysisPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewPlotDataFilterFeature.cpp
)

list(APPEND COMMAND_CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
