set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicfCommandObject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifcCommandFileReader.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
