set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RivCellEdgeEffectGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivNNCGeometryGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivGridPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivTernarySaturationOverlayItem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivReservoirPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivReservoirViewPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivPipeGeometryGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivReservoirSimWellsPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellPathSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellPathPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellPathsPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivSimWellPipesPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellHeadPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivTextureCoordsCreator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivTernaryScalarMapper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivTernaryTextureCoordsCreator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivTernaryScalarMapperEffectGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivScalarMapperUtils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivCellEdgeGeometryUtils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivPipeQuadToSegmentMapper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivSingleCellPartGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivSimWellPipeSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellSpheresPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivObjectSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellConnectionsPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivFishbonesSubsPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivTensorResultPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellFracturePartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Riv3dWellLogPlanePartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Riv3dWellLogCurveGeometryGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellConnectionFactorPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellConnectionFactorGeometryGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellConnectionSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivSimWellConnectionSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Riv3dWellLogDrawSurfaceGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivMeshLinesSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivContourMapProjectionPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivAnnotationsPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivTextAnnotationPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivReachCircleAnnotationPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivReachCircleAnnotationSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivPolylinesAnnotationSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivPolylineGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivMeasurementPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivTextLabelSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivDiskGeometryGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivWellDiskPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivElementVectorResultPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivPolylinePartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivDrawableSpheres.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivBoxGeometryGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivRefinementRegionPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivAnnotationTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivAnnotationSourceInfo.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
