set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimMeasurement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiuMeasurementEventFilter.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
