set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicAddEclipseInputPropertyFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicComputeStatisticsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateGridCaseGroupFromFilesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipseCaseNewGroupExec.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipseCaseNewGroupFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipsePropertyFilterFeatureImpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipsePropertyFilterInsertExec.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipsePropertyFilterInsertFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipsePropertyFilterNewExec.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipsePropertyFilterNewFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportEclipseCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportEclipseCasesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportGridModelFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewStatisticsCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicApplyPropertyFilterAsCellResultFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportEclipseCaseTimeStepFilterFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipsePropertyFilterNewInViewFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipseHideFaultFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipseShowOnlyFaultFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewFaultDistanceResultFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicRenameCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicAddGridCalculationFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateGridCaseEnsemblesFromFilesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicAddLinkedEclipsePropertyFilterFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipseCombinedPropertyFilterNewFeature.cpp
)

list(APPEND COMMAND_CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
