set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimCompletionCellIntersectionCalc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFishbonesCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFishbones.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFishbonesPipeProperties.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFishbonesDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPerforationCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPerforationInterval.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellPathCompletions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellPathCompletionSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEllipseFractureTemplate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFracture.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFractureContainment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFractureContainmentTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFractureExportSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFractureTemplate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCompletionTemplateCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFractureTemplateCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimValveTemplateCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimValveTemplate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMeshFractureTemplate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimThermalFractureTemplate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimStimPlanFractureTemplate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellPathFracture.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellPathFractureCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogCurveCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMswCompletionParameters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimNonDarcyPerforationParameters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellPathValve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimValveCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMultipleValveLocations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellPathAicdParameters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellPathSicdParameters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimDiameterRoughnessInterval.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimDiameterRoughnessIntervalCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCustomSegmentInterval.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCustomSegmentIntervalCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSegmentCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSegmentInterval.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFractureStatistics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFractureStatisticsCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMswSegment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMswSegmentCollection.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
