set(SOURCE_GROUP_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimGenericJob.h
    ${CMAKE_CURRENT_LIST_DIR}/RimOpmFlowJob.h
    ${CMAKE_CURRENT_LIST_DIR}/RimJobCollection.h
    ${CMAKE_CURRENT_LIST_DIR}/RimDeckPositionDlg.h
)

set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimGenericJob.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimOpmFlowJob.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimJobCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimDeckPositionDlg.cpp
)

list(APPEND CODE_HEADER_FILES ${SOURCE_GROUP_HEADER_FILES})

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
