set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RigAccWellFlowCalculator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigEclipseWellLogExtractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigFishbonesGeometry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigGeoMechWellLogExtractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigMswCenterLineCalculator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigOsduWellLogData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigSimulationWellCenterLineCalculator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigSimulationWellCoordsAndMD.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigSimWellData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellAllocationOverTime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellDiskData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellLogCurveData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellLogExtractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellLogIndexDepthOffset.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellPath.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellPathFormations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellPathGeometryExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellPathGeometryTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellPathIntersectionTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellResultBranch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellResultFrame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellResultPoint.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellTargetMapping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellTargetMappingTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellLogData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellLogLasFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigWellLogCsvFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigImportedWellLogData.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
