#!/bin/sh

# Find the installation path. We assume that this script is placed in the installation directory.
INSTALL_PATH=$(dirname "$_")

# Store the users working directory
WORKING_DIR=`pwd`

# Change to application directory
cd "$INSTALL_PATH"

# Start the application making the default file open path become the users cwd

CommandLine="./ResInsight --startdir $WORKING_DIR $@"
exec $CommandLine
