set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogPlotCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogExtractionCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogLasFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogCsvFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimOsduWellLog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogFileUtil.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogChannel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimOsduWellLogChannel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogLasFileCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogRftCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogWbsCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogPlotNameConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogExtractionCurveNameConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogLasFileCurveNameConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogRftCurveNameConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogFileCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogExtractionCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogRftCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogCurveCommonDataSource.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleWellLogs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleWellLogsCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleWellLogCurveSet.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleWellLogStatistics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleWellLogStatisticsCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimRftTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimRftTopologyCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogCurveInfoTextProvider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogCalculatedCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogFileDataLoader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimOsduWellLogDataLoader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimImportedWellLog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimImportedWellLogData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellLogChannelData.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
