set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicCellRangeUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportCarfin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportCarfinUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportFaultsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicAdvancedSnapshotExportFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportToLasFileFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportToLasFileResampleUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSaveEclipseInputPropertyFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSaveEclipseInputVisibleCellsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSaveEclipseInputVisibleCellsUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportEclipseSectorModelFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportEclipseSectorModelUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportSectorModelFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportSectorModelUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicRefinementSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSaveEclipseResultAsInputPropertyExec.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSaveEclipseResultAsInputPropertyFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSnapshotAllPlotsToFileFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSnapshotAllViewsToFileFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSnapshotFilenameGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSnapshotViewToClipboardFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSnapshotViewToFileFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSnapshotViewToPdfFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportSelectedWellPathsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportVisibleWellPathsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportWellPathsUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportLgrFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportLgrUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEclipseCellResultToFileImpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateDepthAdjustedLasFilesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateDepthAdjustedLasFilesUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateDepthAdjustedLasFilesImpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportInpFileFeature.cpp
)

list(APPEND COMMAND_CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
