set(SOURCE_GROUP_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWorkflowJobFeature.h
    ${CMAKE_CURRENT_LIST_DIR}/RicRunWorkflowJobFeature.h
    ${CMAKE_CURRENT_LIST_DIR}/RicCancelWorkflowJobFeature.h
)

set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWorkflowJobFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicRunWorkflowJobFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCancelWorkflowJobFeature.cpp
)

list(APPEND COMMAND_CODE_HEADER_FILES ${SOURCE_GROUP_HEADER_FILES})
list(APPEND COMMAND_CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
