set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimFormationNames.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFormationNamesCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFormationTools.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
