set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimAsciiDataCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimFileSummaryCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimGridSummaryCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCaseMainCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryEnsemble.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCurvesData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCurveAppearanceCalculator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCurveAutoName.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryPlotAxisFormatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCurveCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryPlotTextProvider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryPlotCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCrossPlotCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryTimeAxisProperties.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimObservedSummaryData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryObservedDataFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimObservedEclipseUserData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCalculatedSummaryCurveReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryAddress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCrossPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryPlotSourceStepping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCsvUserData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryPlotNameHelper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleCurveSetCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleCurveSet.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleCurveSetColorManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleCurveFilter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleCurveFilterCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleStatistics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleStatisticsCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimDeltaSummaryCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimDeltaSummaryEnsemble.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimObjectiveFunction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimObjectiveFunctionTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryPlotManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryMultiPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryDataSourceStepping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryNameHelper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMultipleSummaryPlotNameHelper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryAddressCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryMultiPlotCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryPlotControls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleCurveInfoTextProvider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimRftCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCsvSummaryCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryTableCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryTableTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryDeclineCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryRegressionAnalysisCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryAddressSelector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleCrossPlotStatisticsCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryEnsembleTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryPlotReadOut.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
