set(SOURCE_GROUP_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicNewIntersectionBandFeature.h
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteIntersectionBandFeature.h)

set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicNewIntersectionBandFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteIntersectionBandFeature.cpp)

list(APPEND COMMAND_CODE_HEADER_FILES ${SOURCE_GROUP_HEADER_FILES})

list(APPEND COMMAND_CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})

set(COMMAND_QT_MOC_HEADERS
    ${COMMAND_QT_MOC_HEADERS})

source_group(
  "CommandFeature\\Intersection"
  FILES ${SOURCE_GROUP_HEADER_FILES} ${SOURCE_GROUP_SOURCE_FILES}
        ${CMAKE_CURRENT_LIST_DIR}/CMakeLists_files.cmake)
