@startuml

RigMainGrid *-- "1" RigNNCData

RigEclipseCaseData *-- RigMainGrid


RimCase *-- RimTimeStepFilter


RimCase <|- RimEclipseCase
RimEclipseCase <|- RimEclipseResultCase

RimEclipseResultCase *- RigEclipseCaseData

@enduml
