set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RivSeismicSectionPartMgr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivSeismicSectionSourceInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RivTexturePartMgr.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
