set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotTemplateFolderItem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotTemplateFileItem.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
