set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicOpenSummaryPlotEditorFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicOpenSummaryPlotEditorFromDockAreaFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewDefaultSummaryPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewSummaryCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSummaryPlotFeatureImpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDuplicateSummaryPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDuplicateSummaryCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteAsciiDataToSummaryPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteAsciiDataToSummaryPlotFeatureUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicViewZoomAllFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSummaryCurveSwitchAxisFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteSummaryPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteSummaryCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteSummaryCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicAsciiExportSummaryPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewGridTimeHistoryCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSelectSummaryPlotUI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteTimeHistoryCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteAsciiDataCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEditSummaryPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSummaryPlotEditorUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSummaryPlotEditorWidgetCreator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSummaryPlotEditorDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicShowSummaryCurveCalculatorFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicEditSummaryCurveCalculationFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSummaryCurveCalculatorDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSummaryCurveCalculatorUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewSummaryCrossPlotCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewSummaryEnsembleCurveSetFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteEnsembleCurveSetFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewEnsembleCurveFilterFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewDerivedEnsembleFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicClearSourceSteppingSummaryCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSetSourceSteppingSummaryCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicClearSourceSteppingEnsembleCurveSetFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSetSourceSteppingEnsembleCurveSetFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewDerivedSummaryFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewPlotAxisPropertiesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicShowSummaryPlotManagerFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteSummaryMultiPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteSubPlotCtxFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicToggleYAxisLinkingFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicToggleXAxisLinkingFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewSummaryTableFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDuplicateSummaryTableFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateDeclineCurvesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateRegressionAnalysisCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateCrossPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicReplaceSummaryEnsembleFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicReplaceSummaryCaseFeature.cpp
)

list(APPEND COMMAND_CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
