set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicAddWellLogToPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWellLogExtractionCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWellLogRftCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewRftPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewPltPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWellLogFileCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWellLogPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWellLogPlotFeatureImpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWellLogPlotTrackFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicWellLogPlotCurveFeatureImpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicWellLogsImportFileFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteSubPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicWellLogPlotTrackFeatureImpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteWellLogCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteWellLogTrackFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPasteWellLogPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicChangeDataSourceFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicAsciiExportWellLogPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicWellLogFileCloseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicMoveWellLogFilesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicAdd3dWellLogCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicAdd3dWellLogFileCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicAdd3dWellLogRftCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Ric3dWellLogCurveDeleteFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Ric3dWellLogCurvePickEventHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWellBoreStabilityPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWellMeasurementCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewEnsembleWellLogCurveSetFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewRftWellLogPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewRftSegmentWellLogPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewMultiPhaseRftSegmentPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWellLogCalculatedCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateRftPlotsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateRftPlotsFeatureUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateRftCorrelationReportFeature.cpp
)

list(APPEND COMMAND_CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
