set(SOURCE_GROUP_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RigSimulationInputSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/RigSimulationInputTool.h
)

set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RigSimulationInputSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RigSimulationInputTool.cpp
)

list(APPEND CODE_HEADER_FILES ${SOURCE_GROUP_HEADER_FILES})
list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
