set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseCaseCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCaseCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimRegularLegendConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimOilField.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimDataAnalyticsCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimIdenticalGridCaseGroup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseInputProperty.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseInputPropertyCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseInputCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseResultCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimRoffCaseSumo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseResultDefinition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseCellColors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCellEdgeColors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSimWellInView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSimWellInViewCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSimWellInViewTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimScriptCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseStatisticsCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseStatisticsCaseCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCalcScript.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimExportInputPropertySettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimBinaryExportSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Rim3dOverlayInfoConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimHistogramCalculator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimTensorResults.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimReservoirCellResultsStorage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseStatisticsCaseEvaluator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMimeData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMockModelSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimTernaryLegendConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseFaultColors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMudWeightWindowParameters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimViewWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Rim3dView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimGridView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Rim2dIntersectionView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Rim2dIntersectionViewCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimViewManipulator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimViewController.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMainPlotCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimRftPlotCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPltPlotCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMultiPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimDepthTrackPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellBoreStabilityPlot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWbsParameters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimViewLinker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimViewLinkerCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimContextCommandBuilder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimGridCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimRefinementRegion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimRefinementRegionCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotCurveAppearance.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimStackablePlotCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimAdvancedSnapshotExportDefinition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimDockWindowController.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimNamedObject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCheckableNamedObject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCheckableObject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimGridTimeHistoryCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseGeometrySelectionItem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimDialogData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimTimeStepFilter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimUserDefinedCalculation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimUserDefinedCalculationCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimUserDefinedCalculationVariable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCalculation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCalculationCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCalculationVariable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimGridCalculation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimGridCalculationCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimGridCalculationVariable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimStimPlanLegendConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimStimPlanColors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimVirtualPerforationResults.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimLegendConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimNameConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimDataSourceSteppingTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimViewNameConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimReloadCaseTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotAxisPropertiesInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotAxisProperties.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotAxisLogRangeCalculator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimObservedDataCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimObservedFmuRftData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMultiPlotCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellDiskConfig.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimElementVectorResult.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimColorLegendCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimColorLegend.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimColorLegendItem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaOpmParserTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RiaOpmKeywordTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCaseDisplayNameTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCustomObjectiveFunctionCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCustomObjectiveFunction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCustomObjectiveFunctionWeight.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cafTreeNode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMultipleLocations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSurfaceIntersectionBand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSurfaceIntersectionCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSurfaceIntersectionCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseResultAddress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseResultAddressCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimRoffCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseCaseTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimMultipleEclipseResults.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPressureDepthData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseResultDefinitionTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimResultSelectionUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimResultNameAlias.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEmCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPolylinePickerInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseViewCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEclipseCaseEnsemble.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCameraPosition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimWellTargetMapping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimRegularGridCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimGeometrySelectionItem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimCornerPointCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimReservoirGridEnsemble.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimReservoirGridEnsembleBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimReservoirGridEnsembleSumo.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
