/////////////////////////////////////////////////////////////////////////////////
//
//  Copyright (C) 2025-     Equinor ASA
//
//  ResInsight is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ResInsight is distributed in the hope that it will be useful, but WITHOUT ANY
//  WARRANTY; without even the implied warranty of MERCHANTABILITY or
//  FITNESS FOR A PARTICULAR PURPOSE.
//
//  See the GNU General Public License at <http://www.gnu.org/licenses/gpl.html>
//  for more details.
//
/////////////////////////////////////////////////////////////////////////////////

#include "RicScheduleDataGenerator.h"

#include "RimEclipseCase.h"
#include "RimWellEventControl.h"
#include "RimWellEventPerf.h"
#include "RimWellEventState.h"
#include "RimWellEventTimeline.h"
#include "RimWellEventTubing.h"
#include "RimWellEventType.h"
#include "RimWellEventValve.h"
#include "RimWellPath.h"

#include <QLocale>

#include <algorithm>
#include <set>

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateSchedule( RimEclipseCase*                  eclipseCase,
                                                    const std::vector<RimWellPath*>& wellPaths,
                                                    const std::vector<QDateTime>&    dates,
                                                    const Options&                   options )
{
    QString result;

    // Header
    result += "-- Generated by ResInsight\n";
    result += "-- Schedule data based on well events\n";
    result += "--\n";

    // List wells
    if ( options.includeComments )
    {
        result += "-- Wells: ";
        QStringList wellNames;
        for ( const auto* well : wellPaths )
        {
            if ( well )
            {
                wellNames.append( well->name() );
            }
        }
        result += wellNames.join( ", " );
        result += "\n--\n\n";
    }

    // Sort dates chronologically
    std::vector<QDateTime> sortedDates = dates;
    std::sort( sortedDates.begin(), sortedDates.end() );

    // Generate section for each date
    for ( const auto& date : sortedDates )
    {
        QString dateSection = generateDateSection( eclipseCase, wellPaths, date, options );
        if ( !dateSection.isEmpty() )
        {
            result += dateSection;
        }
    }

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
std::vector<QDateTime> RicScheduleDataGenerator::collectAllDates( const std::vector<RimWellPath*>& wellPaths )
{
    std::set<QDateTime> uniqueDates;

    for ( const auto* well : wellPaths )
    {
        if ( well && well->eventTimeline() )
        {
            auto dates = well->eventTimeline()->getAllEventDates();
            for ( const auto& date : dates )
            {
                uniqueDates.insert( date );
            }
        }
    }

    return std::vector<QDateTime>( uniqueDates.begin(), uniqueDates.end() );
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateDateSection( RimEclipseCase*                  eclipseCase,
                                                       const std::vector<RimWellPath*>& wellPaths,
                                                       const QDateTime&                 date,
                                                       const Options&                   options )
{
    QString result;

    // Generate DATES keyword
    result += generateDatesKeyword( date );

    // Collect all output for this date
    QString compdatData;
    QString mswData;
    QString wellControlData;

    for ( auto* well : wellPaths )
    {
        if ( !well )
            continue;

        if ( options.includeCompdat )
        {
            QString wellCompdat = generateCompdatForWell( eclipseCase, well, date );
            if ( !wellCompdat.isEmpty() )
            {
                compdatData += wellCompdat;
            }
        }

        if ( options.includeMsw )
        {
            QString wellMsw = generateMswForWell( eclipseCase, well, date );
            if ( !wellMsw.isEmpty() )
            {
                mswData += wellMsw;
            }
        }

        if ( options.includeWellControl )
        {
            QString wellControl = generateWellControlForWell( well, date );
            if ( !wellControl.isEmpty() )
            {
                wellControlData += wellControl;
            }
        }
    }

    // Output collected data
    if ( !compdatData.isEmpty() )
    {
        result += compdatData;
    }

    if ( !mswData.isEmpty() )
    {
        result += mswData;
    }

    if ( !wellControlData.isEmpty() )
    {
        result += wellControlData;
    }

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateDatesKeyword( const QDateTime& date )
{
    // Format: DATES
    //  1 JAN 2024 /
    // /

    QLocale locale( QLocale::English );
    QString day   = QString::number( date.date().day() );
    QString month = locale.monthName( date.date().month(), QLocale::ShortFormat ).toUpper();
    QString year  = QString::number( date.date().year() );

    QString result = QString( "DATES\n %1 %2 %3 /\n/\n\n" ).arg( day ).arg( month ).arg( year );

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateCompdatForWell( RimEclipseCase* eclipseCase, RimWellPath* well, const QDateTime& date )
{
    if ( !well || !well->eventTimeline() )
        return QString();

    // Get perforation events at this exact date
    auto events = well->eventTimeline()->getEventsAtDate( date );

    QString perfEvents;
    for ( auto* event : events )
    {
        if ( event->eventType() == RimWellEvent::EventType::PERF )
        {
            perfEvents += event->generateScheduleKeyword( well->name() );
        }
    }

    if ( perfEvents.isEmpty() )
        return QString();

    // Note: Actual COMPDAT generation requires grid intersection calculations
    // This is a placeholder that generates comments with event data
    QString result = QString( "-- COMPDAT events for %1 at %2\n" ).arg( well->name() ).arg( date.toString( "yyyy-MM-dd" ) );
    result += perfEvents;
    result += "\n";

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateMswForWell( RimEclipseCase* eclipseCase, RimWellPath* well, const QDateTime& date )
{
    if ( !well || !well->eventTimeline() )
        return QString();

    // Get valve and tubing events at this exact date
    auto events = well->eventTimeline()->getEventsAtDate( date );

    QString valveEvents;
    QString tubingEvents;

    for ( auto* event : events )
    {
        if ( event->eventType() == RimWellEvent::EventType::VALVE )
        {
            valveEvents += event->generateScheduleKeyword( well->name() );
        }
        else if ( event->eventType() == RimWellEvent::EventType::TUBING )
        {
            tubingEvents += event->generateScheduleKeyword( well->name() );
        }
    }

    if ( valveEvents.isEmpty() && tubingEvents.isEmpty() )
        return QString();

    QString result;

    if ( !tubingEvents.isEmpty() )
    {
        result += QString( "-- WELSEGS tubing events for %1 at %2\n" ).arg( well->name() ).arg( date.toString( "yyyy-MM-dd" ) );
        result += tubingEvents;
    }

    if ( !valveEvents.isEmpty() )
    {
        result += QString( "-- WSEGVALV events for %1 at %2\n" ).arg( well->name() ).arg( date.toString( "yyyy-MM-dd" ) );
        result += valveEvents;
    }

    result += "\n";

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateWellControlForWell( RimWellPath* well, const QDateTime& date )
{
    if ( !well || !well->eventTimeline() )
        return QString();

    // Get state and control events at this exact date
    auto events = well->eventTimeline()->getEventsAtDate( date );

    QString result;

    for ( auto* event : events )
    {
        if ( event->eventType() == RimWellEvent::EventType::WSTATE )
        {
            result += event->generateScheduleKeyword( well->name() );
        }
        else if ( event->eventType() == RimWellEvent::EventType::WCONTROL )
        {
            result += event->generateScheduleKeyword( well->name() );
        }
        else if ( event->eventType() == RimWellEvent::EventType::WTYPE )
        {
            result += event->generateScheduleKeyword( well->name() );
        }
    }

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
std::vector<RimWellEvent*> RicScheduleDataGenerator::getActiveEventsAtDate( RimWellPath* well, const QDateTime& date )
{
    if ( !well || !well->eventTimeline() )
        return {};

    return well->eventTimeline()->getEventsUpToDate( date );
}
