/////////////////////////////////////////////////////////////////////////////////
//
//  Copyright (C) 2025-     Equinor ASA
//
//  ResInsight is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ResInsight is distributed in the hope that it will be useful, but WITHOUT ANY
//  WARRANTY; without even the implied warranty of MERCHANTABILITY or
//  FITNESS FOR A PARTICULAR PURPOSE.
//
//  See the GNU General Public License at <http://www.gnu.org/licenses/gpl.html>
//  for more details.
//
/////////////////////////////////////////////////////////////////////////////////

#include "RicScheduleDataGenerator.h"

#include "ReservoirDataModel/CompletionsMsw/RigMswTableData.h"

#include "RicWellPathExportCompletionDataFeatureImpl.h"
#include "RicWellPathExportMswTableData.h"

#include "RifEventKeywordFormatter.h"

#include "ProjectDataModel/Jobs/RimKeywordFactory.h"
#include "RimEclipseCase.h"
#include "RimKeywordEvent.h"
#include "RimWellEventTimeline.h"
#include "RimWellPath.h"
#include "RimWellPathCompletionSettings.h"

#include "opm/input/eclipse/Deck/DeckKeyword.hpp"

#include <map>
#include <set>

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateSchedule( const RimWellEventTimeline&      timeline,
                                                    RimEclipseCase&                  eclipseCase,
                                                    const std::vector<RimWellPath*>& wellPaths,
                                                    const std::vector<QDateTime>&    dates )
{
    QString result;

    // Header
    result += "-- Generated by ResInsight\n";
    result += "-- Schedule data based on well events\n";
    result += "--\n";

    // Generate section for each date
    for ( const auto& date : dates )
    {
        QString dateSection = generateDateSection( timeline, eclipseCase, wellPaths, date );
        if ( !dateSection.isEmpty() )
        {
            result += dateSection;
        }
    }

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
std::vector<QDateTime> RicScheduleDataGenerator::collectAllDates( const RimWellEventTimeline&      timeline,
                                                                  const std::vector<RimWellPath*>& wellPaths )
{
    std::set<QDateTime> uniqueDates;

    for ( const auto* well : wellPaths )
    {
        if ( well )
        {
            auto dates = timeline.getAllEventDates();
            for ( const auto& date : dates )
            {
                uniqueDates.insert( date );
            }
        }
    }

    return std::vector<QDateTime>( uniqueDates.begin(), uniqueDates.end() );
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateDateSection( const RimWellEventTimeline&      timeline,
                                                       RimEclipseCase&                  eclipseCase,
                                                       const std::vector<RimWellPath*>& wellPaths,
                                                       const QDateTime&                 date )
{
    // Keyword priority order for output
    static const std::vector<QString> keywordOrder = { "WELSPECS",
                                                       "COMPORD",
                                                       "GRUPTREE",
                                                       "COMPDAT",
                                                       "COMPLUMP",
                                                       "WELSEGS",
                                                       "COMPSEGS",
                                                       "WCONHIST",
                                                       "WCONINJH",
                                                       "WCONPROD",
                                                       "WCONINJE",
                                                       "WRFTPLT",
                                                       "TUNING",
                                                       "RPTSCHED",
                                                       "RPTRST",
                                                       "WSEGVALV",
                                                       "WSEGAICD" };

    QString result;

    // Generate DATES keyword
    result += RimKeywordFactory::deckKeywordToString( RimKeywordFactory::datesKeyword( date ) ) + "\n";

    // Collect all keyword output into a map keyed by keyword name
    std::map<QString, QString> keywordBlocks;

    for ( auto* well : wellPaths )
    {
        if ( !well ) continue;

        QString welspecsKw = generateWelspecsForWell( timeline, eclipseCase, *well, date );
        if ( !welspecsKw.isEmpty() )
        {
            keywordBlocks["WELSPECS"] += welspecsKw;
        }

        QString wellCompdat = generateCompdatForWell( timeline, eclipseCase, *well, date );
        if ( !wellCompdat.isEmpty() )
        {
            keywordBlocks["COMPDAT"] += wellCompdat;
        }

        generateMswForWell( timeline, eclipseCase, *well, date, keywordBlocks );
        generateWellControlForWell( timeline, *well, date, keywordBlocks );
    }

    // Process schedule-level keyword events (not tied to a specific well)
    auto events = timeline.getEventsAtDate( date );
    for ( auto* event : events )
    {
        if ( event->eventType() == RimWellEvent::EventType::SCHEDULE_KEYWORD )
        {
            auto* keywordEvent = dynamic_cast<RimKeywordEvent*>( event );
            if ( keywordEvent )
            {
                QString keywordStr = keywordEvent->generateScheduleKeyword( "" );
                if ( !keywordStr.isEmpty() )
                {
                    keywordBlocks[keywordEvent->keywordName().toUpper()] += keywordStr + "\n";
                }
            }
        }
    }

    // Output keywords in priority order
    std::set<QString> emitted;
    for ( const auto& kw : keywordOrder )
    {
        auto it = keywordBlocks.find( kw );
        if ( it != keywordBlocks.end() && !it->second.isEmpty() )
        {
            result += it->second;
            emitted.insert( kw );
        }
    }

    // Output remaining keywords not in priority list
    for ( const auto& [kw, data] : keywordBlocks )
    {
        if ( emitted.find( kw ) == emitted.end() && !data.isEmpty() )
        {
            result += data;
        }
    }

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateWelspecsForWell( const RimWellEventTimeline& timeline,
                                                           RimEclipseCase&             eclipseCase,
                                                           RimWellPath&                well,
                                                           const QDateTime&            date )
{
    // Get perforation events at this exact date for this well
    auto events = timeline.getEventsAtDate( date );

    bool hasEvents = false;
    for ( auto* event : events )
    {
        if ( ( event->eventType() == RimWellEvent::EventType::PERF || event->eventType() == RimWellEvent::EventType::VALVE ||
               event->eventType() == RimWellEvent::EventType::TUBING ) &&
             event->wellName() == well.name() )
        {
            hasEvents = true;
            break;
        }
    }

    if ( !hasEvents ) return QString();

    std::string wellGroupName = well.completionSettings()->groupNameForExport().toStdString();
    auto        welspecsKw    = RimKeywordFactory::welspecsKeyword( wellGroupName, &eclipseCase, &well );

    QString result;
    result += RimKeywordFactory::deckKeywordToString( welspecsKw );
    result += "\n";

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateCompdatForWell( const RimWellEventTimeline& timeline,
                                                          RimEclipseCase&             eclipseCase,
                                                          RimWellPath&                well,
                                                          const QDateTime&            date )
{
    // Get perforation events at this exact date for this well
    auto events = timeline.getEventsAtDate( date );

    bool hasPerfEvents = false;
    for ( auto* event : events )
    {
        if ( event->eventType() == RimWellEvent::EventType::PERF && event->wellName() == well.name() )
        {
            hasPerfEvents = true;
            break;
        }
    }

    if ( !hasPerfEvents ) return QString();

    auto compdata = RicWellPathExportCompletionDataFeatureImpl::completionDataForWellPath( &well, &eclipseCase, date );
    auto wellName = well.completionSettings()->wellNameForExport().toStdString();

    auto    compdatKw = RimKeywordFactory::compdatKeyword( compdata, wellName );
    QString result;
    result += RimKeywordFactory::deckKeywordToString( compdatKw );
    result += "\n";

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
void RicScheduleDataGenerator::generateMswForWell( const RimWellEventTimeline& timeline,
                                                   RimEclipseCase&             eclipseCase,
                                                   RimWellPath&                wellPath,
                                                   const QDateTime&            date,
                                                   std::map<QString, QString>& keywordBlocks )
{
    // Check if the well has MSW configured (from any previous tubing events applied via set_timestamp)
    // If MSW is enabled, we should generate WELSEGS/COMPSEGS instead of COMPDAT
    auto* mswParams = wellPath.mswCompletionParameters();
    if ( !mswParams )
    {
        return;
    }

    // Also check if there are valve or tubing events at this specific date for this well
    // (these trigger updates to the MSW configuration)
    auto events        = timeline.getEventsAtDate( date );
    bool hasMswEvents  = false;
    bool hasPerfEvents = false;
    for ( auto* event : events )
    {
        if ( event->wellName() != wellPath.name() ) continue;

        if ( event->eventType() == RimWellEvent::EventType::VALVE || event->eventType() == RimWellEvent::EventType::TUBING )
        {
            hasMswEvents = true;
        }
        else if ( event->eventType() == RimWellEvent::EventType::PERF )
        {
            hasPerfEvents = true;
        }
    }

    // Only generate MSW output if there are events at this specific date for this well
    // This ensures wells only appear in schedule sections at their event dates
    if ( !hasMswEvents && !hasPerfEvents )
    {
        return;
    }

    // Extract MSW data using the existing infrastructure
    // Pass the export date to filter valve/perforation output based on their creation dates
    bool exportAfterMainBore = true;
    auto mswDataResult       = RicWellPathExportMswTableData::extractSingleWellMswData( &eclipseCase,
                                                                                  &wellPath,
                                                                                  exportAfterMainBore,
                                                                                  RicWellPathExportMswTableData::CompletionType::ALL,
                                                                                  date );

    if ( !mswDataResult.has_value() ) return;

    const auto& mswData = mswDataResult.value();

    // Generate WELSEGS keyword
    int              maxSegments = 0;
    int              maxBranches = 0;
    Opm::DeckKeyword welsegsKw   = RimKeywordFactory::welsegsKeyword( mswData, maxSegments, maxBranches );
    if ( welsegsKw.isDataKeyword() || welsegsKw.size() > 0 )
    {
        keywordBlocks["WELSEGS"] += RimKeywordFactory::deckKeywordToString( welsegsKw ) + "\n";
    }

    // Generate COMPSEGS keyword
    Opm::DeckKeyword compsegsKw = RimKeywordFactory::compsegsKeyword( mswData );
    if ( compsegsKw.isDataKeyword() || compsegsKw.size() > 0 )
    {
        keywordBlocks["COMPSEGS"] += RimKeywordFactory::deckKeywordToString( compsegsKw ) + "\n";
    }

    // Generate WSEGVALV keyword (for valve events)
    Opm::DeckKeyword wsegvalvKw = RimKeywordFactory::wsegvalvKeyword( mswData );
    if ( wsegvalvKw.isDataKeyword() || wsegvalvKw.size() > 0 )
    {
        keywordBlocks["WSEGVALV"] += RimKeywordFactory::deckKeywordToString( wsegvalvKw ) + "\n";
    }

    // Generate WSEGAICD keyword (if AICD data present)
    Opm::DeckKeyword wsegaicdKw = RimKeywordFactory::wsegaicdKeyword( mswData );
    if ( wsegaicdKw.isDataKeyword() || wsegaicdKw.size() > 0 )
    {
        keywordBlocks["WSEGAICD"] += RimKeywordFactory::deckKeywordToString( wsegaicdKw ) + "\n";
    }
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
void RicScheduleDataGenerator::generateWellControlForWell( const RimWellEventTimeline& timeline,
                                                           const RimWellPath&          well,
                                                           const QDateTime&            date,
                                                           std::map<QString, QString>& keywordBlocks )
{
    // Get state and control events at this exact date for this well
    auto events = timeline.getEventsAtDate( date );

    for ( auto* event : events )
    {
        if ( event->wellName() != well.name() ) continue;

        QString keywordStr = RifEventKeywordFormatter::formatWellEvent( event, well.name() );
        if ( !keywordStr.isEmpty() )
        {
            QString kwName = extractKeywordName( keywordStr );
            if ( !kwName.isEmpty() )
            {
                keywordBlocks[kwName] += keywordStr + "\n";
            }
        }
    }
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::extractKeywordName( const QString& block )
{
    const auto lines = block.split( '\n' );
    for ( const auto& line : lines )
    {
        QString trimmed = line.trimmed();
        if ( !trimmed.isEmpty() && !trimmed.startsWith( "--" ) )
        {
            return trimmed;
        }
    }
    return {};
}
