/////////////////////////////////////////////////////////////////////////////////
//
//  Copyright (C) 2025-     Equinor ASA
//
//  ResInsight is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ResInsight is distributed in the hope that it will be useful, but WITHOUT ANY
//  WARRANTY; without even the implied warranty of MERCHANTABILITY or
//  FITNESS FOR A PARTICULAR PURPOSE.
//
//  See the GNU General Public License at <http://www.gnu.org/licenses/gpl.html>
//  for more details.
//
/////////////////////////////////////////////////////////////////////////////////

#include "RicScheduleDataGenerator.h"

#include "ReservoirDataModel/CompletionsMsw/RigMswTableData.h"

#include "RicWellPathExportCompletionDataFeatureImpl.h"
#include "RicWellPathExportMswTableData.h"

#include "RifEventKeywordFormatter.h"

#include "ProjectDataModel/Jobs/RimKeywordFactory.h"
#include "RimEclipseCase.h"
#include "RimKeywordEvent.h"
#include "RimWellEventTimeline.h"
#include "RimWellPath.h"
#include "RimWellPathCompletionSettings.h"

#include "opm/input/eclipse/Deck/DeckKeyword.hpp"
#include "opm/input/eclipse/Deck/DeckRecord.hpp"

#include <map>
#include <set>

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateSchedule( const RimWellEventTimeline&         timeline,
                                                    RimEclipseCase&                     eclipseCase,
                                                    const std::vector<RimWellPath*>&    wellPaths,
                                                    const std::vector<QDateTime>&       dates,
                                                    const std::set<const RimWellPath*>& mswWells )
{
    QString result;

    // Header
    result += "-- Generated by ResInsight\n";
    result += "-- Schedule data based on well events\n";
    result += "--\n";

    // Generate section for each date
    for ( const auto& date : dates )
    {
        QString dateSection = generateDateSection( timeline, eclipseCase, wellPaths, date, mswWells );
        if ( !dateSection.isEmpty() )
        {
            result += dateSection;
        }
    }

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
std::vector<QDateTime> RicScheduleDataGenerator::collectAllDates( const RimWellEventTimeline&      timeline,
                                                                  const std::vector<RimWellPath*>& wellPaths )
{
    std::set<QDateTime> uniqueDates;

    for ( const auto* well : wellPaths )
    {
        if ( well )
        {
            auto dates = timeline.getAllEventDates();
            for ( const auto& date : dates )
            {
                uniqueDates.insert( date );
            }
        }
    }

    return std::vector<QDateTime>( uniqueDates.begin(), uniqueDates.end() );
}

//--------------------------------------------------------------------------------------------------
/// Append the records of `kw` into the entry for `name`, creating that entry from a copy of `kw`
/// on first encounter so the accumulated DeckKeyword is bound to the right ParserKeyword.
//--------------------------------------------------------------------------------------------------
void RicScheduleDataGenerator::mergeKeyword( std::map<QString, Opm::DeckKeyword>& acc, const QString& name, Opm::DeckKeyword kw )
{
    if ( kw.size() == 0 && !kw.isDataKeyword() ) return;

    auto it = acc.find( name );
    if ( it == acc.end() )
    {
        acc.emplace( name, std::move( kw ) );
        return;
    }
    for ( const auto& rec : kw )
    {
        it->second.addRecord( Opm::DeckRecord( rec ) );
    }
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
QString RicScheduleDataGenerator::generateDateSection( const RimWellEventTimeline&         timeline,
                                                       RimEclipseCase&                     eclipseCase,
                                                       const std::vector<RimWellPath*>&    wellPaths,
                                                       const QDateTime&                    date,
                                                       const std::set<const RimWellPath*>& mswWells )
{
    // Keyword priority order for output
    static const std::vector<QString> keywordOrder = { "WELSPECS",
                                                       "COMPORD",
                                                       "GRUPTREE",
                                                       "COMPDAT",
                                                       "COMPLUMP",
                                                       "WELSEGS",
                                                       "COMPSEGS",
                                                       "WCONHIST",
                                                       "WCONINJH",
                                                       "WCONPROD",
                                                       "WCONINJE",
                                                       "WRFTPLT",
                                                       "TUNING",
                                                       "RPTSCHED",
                                                       "RPTRST",
                                                       "WSEGVALV",
                                                       "WSEGAICD" };

    QString result;

    // Generate DATES keyword
    result += RimKeywordFactory::deckKeywordToString( RimKeywordFactory::datesKeyword( date ) ) + "\n";

    // Records for each keyword name are accumulated across wells, then serialised once below.
    std::map<QString, Opm::DeckKeyword> keywordBlocks;

    // WELSEGS and COMPSEGS cannot be merged across wells: each block carries a per-well header
    // record followed by that well's segment records, so they are kept as separate per-well blocks
    // (keyed by keyword name, preserving well order) and serialised individually.
    std::map<QString, std::vector<Opm::DeckKeyword>> unmergedBlocks;

    for ( auto* well : wellPaths )
    {
        if ( !well ) continue;

        if ( auto welspecs = generateWelspecsForWell( timeline, eclipseCase, *well, date ) )
        {
            mergeKeyword( keywordBlocks, "WELSPECS", std::move( *welspecs ) );
        }

        generateCompletionsForWell( timeline, eclipseCase, *well, date, keywordBlocks );

        generateMswForWell( timeline, eclipseCase, *well, date, keywordBlocks, unmergedBlocks, mswWells );
        generateWellControlForWell( timeline, *well, date, keywordBlocks );
    }

    // Schedule-level keyword events (not tied to a specific well)
    auto events = timeline.getEventsAtDate( date );
    for ( auto* event : events )
    {
        if ( event->eventType() != RimWellEvent::EventType::SCHEDULE_KEYWORD ) continue;
        auto* keywordEvent = dynamic_cast<RimKeywordEvent*>( event );
        if ( !keywordEvent ) continue;
        if ( auto kw = keywordEvent->generateDeckKeyword( "" ) )
        {
            mergeKeyword( keywordBlocks, keywordEvent->keywordName().toUpper(), std::move( *kw ) );
        }
    }

    auto appendKeywordText = [&]( const Opm::DeckKeyword& kw )
    {
        if ( kw.size() == 0 && !kw.isDataKeyword() ) return;
        result += RimKeywordFactory::deckKeywordToString( kw );
        result += "\n";
    };

    auto appendUnmergedBlocks = [&]( const QString& name )
    {
        auto it = unmergedBlocks.find( name );
        if ( it == unmergedBlocks.end() ) return;
        for ( const auto& kw : it->second )
        {
            appendKeywordText( kw );
        }
    };

    // Output keywords in priority order
    std::set<QString> emitted;
    for ( const auto& kw : keywordOrder )
    {
        if ( auto it = keywordBlocks.find( kw ); it != keywordBlocks.end() )
        {
            appendKeywordText( it->second );
        }
        appendUnmergedBlocks( kw );
        emitted.insert( kw );
    }

    // Output remaining keywords not in the priority list
    for ( const auto& [kw, deckKw] : keywordBlocks )
    {
        if ( emitted.contains( kw ) ) continue;
        appendKeywordText( deckKw );
    }
    for ( const auto& [kw, blocks] : unmergedBlocks )
    {
        if ( emitted.contains( kw ) ) continue;
        for ( const auto& deckKw : blocks )
        {
            appendKeywordText( deckKw );
        }
    }

    return result;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
std::optional<Opm::DeckKeyword> RicScheduleDataGenerator::generateWelspecsForWell( const RimWellEventTimeline& timeline,
                                                                                   RimEclipseCase&             eclipseCase,
                                                                                   RimWellPath&                well,
                                                                                   const QDateTime&            date )
{
    auto events = timeline.getEventsAtDate( date );

    bool hasEvents = false;
    for ( auto* event : events )
    {
        if ( ( event->eventType() == RimWellEvent::EventType::PERF || event->eventType() == RimWellEvent::EventType::VALVE ||
               event->eventType() == RimWellEvent::EventType::TUBING ) &&
             event->wellName() == well.name() )
        {
            hasEvents = true;
            break;
        }
    }

    if ( !hasEvents ) return std::nullopt;

    std::string wellGroupName = well.completionSettings()->groupNameForExport().toStdString();
    auto        welspecsKw    = RimKeywordFactory::welspecsKeyword( wellGroupName, &eclipseCase, &well );
    if ( welspecsKw.name().empty() ) return std::nullopt;
    return welspecsKw;
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
void RicScheduleDataGenerator::generateCompletionsForWell( const RimWellEventTimeline&          timeline,
                                                           RimEclipseCase&                      eclipseCase,
                                                           RimWellPath&                         well,
                                                           const QDateTime&                     date,
                                                           std::map<QString, Opm::DeckKeyword>& keywordBlocks )
{
    auto events = timeline.getEventsAtDate( date );

    bool hasPerfEvents = false;
    for ( auto* event : events )
    {
        if ( event->eventType() == RimWellEvent::EventType::PERF && event->wellName() == well.name() )
        {
            hasPerfEvents = true;
            break;
        }
    }

    if ( !hasPerfEvents ) return;

    // Completion data is computed once and feeds both COMPDAT and COMPLUMP (the latter only emits
    // records whose perforation has a completion number assigned). Both keywords merge across wells.
    auto compdata = RicWellPathExportCompletionDataFeatureImpl::completionDataForWellPath( &well, &eclipseCase, date );
    auto wellName = well.completionSettings()->wellNameForExport().toStdString();

    mergeKeyword( keywordBlocks, "COMPDAT", RimKeywordFactory::compdatKeyword( compdata, wellName ) );
    mergeKeyword( keywordBlocks, "COMPLUMP", RimKeywordFactory::complumpKeyword( compdata, wellName ) );
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
void RicScheduleDataGenerator::generateMswForWell( const RimWellEventTimeline&                       timeline,
                                                   RimEclipseCase&                                   eclipseCase,
                                                   RimWellPath&                                      wellPath,
                                                   const QDateTime&                                  date,
                                                   std::map<QString, Opm::DeckKeyword>&              keywordBlocks,
                                                   std::map<QString, std::vector<Opm::DeckKeyword>>& unmergedBlocks,
                                                   const std::set<const RimWellPath*>&               mswWells )
{
    // MSW keywords are exported only for the wells the caller explicitly requested.
    if ( !mswWells.contains( &wellPath ) )
    {
        return;
    }

    auto* mswParams = wellPath.mswCompletionParameters();
    if ( !mswParams )
    {
        return;
    }

    // MSW is generated only when there are valve/tubing/perforation events at this exact date.
    auto events        = timeline.getEventsAtDate( date );
    bool hasMswEvents  = false;
    bool hasPerfEvents = false;
    for ( auto* event : events )
    {
        if ( event->wellName() != wellPath.name() ) continue;

        if ( event->eventType() == RimWellEvent::EventType::VALVE || event->eventType() == RimWellEvent::EventType::TUBING )
        {
            hasMswEvents = true;
        }
        else if ( event->eventType() == RimWellEvent::EventType::PERF )
        {
            hasPerfEvents = true;
        }
    }

    if ( !hasMswEvents && !hasPerfEvents )
    {
        return;
    }

    bool exportAfterMainBore = true;
    auto mswDataResult       = RicWellPathExportMswTableData::extractSingleWellMswData( &eclipseCase,
                                                                                  &wellPath,
                                                                                  exportAfterMainBore,
                                                                                  RicWellPathExportMswTableData::CompletionType::ALL,
                                                                                  date );

    if ( !mswDataResult.has_value() ) return;

    const auto& mswData = mswDataResult.value();

    // WELSEGS and COMPSEGS are not merged across wells (see generateDateSection): each well keeps
    // its own block, appended in well order.
    auto appendUnmerged = [&unmergedBlocks]( const QString& name, Opm::DeckKeyword kw )
    {
        if ( kw.size() == 0 && !kw.isDataKeyword() ) return;
        unmergedBlocks[name].push_back( std::move( kw ) );
    };

    int  maxSegments = 0;
    int  maxBranches = 0;
    auto welsegsKw   = RimKeywordFactory::welsegsKeyword( mswData, maxSegments, maxBranches );
    appendUnmerged( "WELSEGS", std::move( welsegsKw ) );

    auto compsegsKw = RimKeywordFactory::compsegsKeyword( mswData );
    appendUnmerged( "COMPSEGS", std::move( compsegsKw ) );

    auto wsegvalvKw = RimKeywordFactory::wsegvalvKeyword( mswData );
    mergeKeyword( keywordBlocks, "WSEGVALV", std::move( wsegvalvKw ) );

    auto wsegaicdKw = RimKeywordFactory::wsegaicdKeyword( mswData );
    mergeKeyword( keywordBlocks, "WSEGAICD", std::move( wsegaicdKw ) );
}

//--------------------------------------------------------------------------------------------------
///
//--------------------------------------------------------------------------------------------------
void RicScheduleDataGenerator::generateWellControlForWell( const RimWellEventTimeline&          timeline,
                                                           const RimWellPath&                   well,
                                                           const QDateTime&                     date,
                                                           std::map<QString, Opm::DeckKeyword>& keywordBlocks )
{
    auto events = timeline.getEventsAtDate( date );

    for ( auto* event : events )
    {
        if ( event->wellName() != well.name() ) continue;

        auto kw = RifEventKeywordFormatter::buildWellEvent( event, well.name() );
        if ( !kw ) continue;

        const QString name = QString::fromStdString( kw->name() );
        if ( name.isEmpty() ) continue;
        mergeKeyword( keywordBlocks, name, std::move( *kw ) );
    }
}
