set(SOURCE_GROUP_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicToggleMeasurementModeFeature.h
    ${CMAKE_CURRENT_LIST_DIR}/RicMeasurementPickEventHandler.h
)

set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicToggleMeasurementModeFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicMeasurementPickEventHandler.cpp
)

list(APPEND COMMAND_CODE_HEADER_FILES ${SOURCE_GROUP_HEADER_FILES})
list(APPEND COMMAND_CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})

