set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicWellLogTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCloseCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCloseSummaryCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCloseSummaryCaseInCollectionFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCloseObservedDataFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewViewFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewContourMapViewFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportFaciesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportFormationNamesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicReloadFormationNamesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicReloadWellPathFormationNamesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicHideIntersectionFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicHideIntersectionBoxFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportElementPropertyFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSelectColorResult.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicTogglePerspectiveViewFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportSummaryCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportSummaryCasesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportObservedDataFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportObservedFmuDataFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportGeneralDataFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportFeatureImpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSelectOrCreateViewFeatureImpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Ric3dViewPickEventHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicContourMapPickEventHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicVec3dPickEventHandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteItemExec.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteItemExecData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteItemFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteSubItemsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteSummaryCaseCollectionFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteWellMeasurementFilePathFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicReloadWellMeasurementsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicWellMeasurementImportTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportElasticPropertiesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicElasticPropertiesImportTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicFaciesPropertiesImportTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCloseSourSimDataFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicReloadCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicReplaceCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicReloadSummaryCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicFlyToObjectFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicRecursiveFileSearchDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicSummaryCaseRestartDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportEnsembleFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportSummaryGroupFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportEnsembleSurfaceFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportEnsembleWellLogsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicResampleDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateTemporaryLgrFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteTemporaryLgrsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewRefinementRegionFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportContourMapToTextFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportContourMapToTextUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportStimPlanModelToFileFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicStackSelectedCurvesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicUnstackSelectedCurvesFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicThemeColorEditorFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportVfpDataFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewCustomObjectiveFunctionFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewCustomObjectiveFunctionWeightFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewPressureTableItemFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeletePressureTableItemFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportGridModelFromSummaryCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportGridModelFromSummaryCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateEnsembleSurfaceFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateEnsembleSurfaceUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateEnsembleWellLogFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateEnsembleWellLogUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateSurfaceIntersectionBandFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateSurfaceIntersectionCurveFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicShowGridCalculatorFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicUserDefinedCalculatorDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicGridCalculatorDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicGridCalculatorUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCalculatorWidgetCreator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicUserDefinedCalculatorUi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicShowDataSourcesForRealization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicDeleteUncheckedSubItemsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicRenameSummaryCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportPressureDepthDataFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicReloadPressureDepthDataFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportRevealSummaryCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportStimPlanSummaryCaseFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCopyGridStatisticsToClipboardFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportGridCalculationExpressionsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportGridCalculationExpressionsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicExportSummaryCalculationExpressionsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportSummaryCalculationExpressionsFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportWellLogCsvFileFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportWellLogOsduFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewViewForGridEnsembleFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewCustomVfpPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewWellTargetMappingFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewStatisticsContourMapFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewStatisticsContourMapViewFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateContourMapPolygonFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateContourMapPolygonAdvancedFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateContourMapPolygonTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicPolygonFromImageDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateSummaryEnsembleFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportGridAndSummaryEnsembleDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicImportGridAndSummaryEnsembleFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicHistogramPlotTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateGridStatisticsPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicNewNestedCollectionFeature.cpp
)

list(APPEND COMMAND_CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
