set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicfCloseProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfCommandFileExecutor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfComputeCaseGroupStatistics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportMsw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportMultiCaseSnapshots.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportProperty.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportSnapshots.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportWellPathCompletions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfLoadCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfOpenProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfReplaceCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfReplaceSourceCases.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfRunOctaveScript.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfSetExportFolder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfSetMainWindowSize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfSetPlotWindowSize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfSetStartDir.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfSetTimeStep.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfScaleFractureTemplate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfSetFractureContainment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfCreateMultipleFractures.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportWellPaths.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportVisibleCells.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportPropertyInViews.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportLgrForCompletions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfCreateLgrForCompletions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfApplicationTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfCreateSaturationPressurePlots.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportFlowCharacteristics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfCreateGridCaseGroup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfCreateStatisticsCase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfCreateView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfCloneView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfCreateWellBoreStabilityPlotFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfImportWellLogFiles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfImportFormationNames.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicfExportWellLogPlotData.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
