
set (SOURCE_GROUP_HEADER_FILES
${CMAKE_CURRENT_LIST_DIR}/RimEclipseCaseCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimCaseCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimCellFilter.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipsePropertyFilter.h
${CMAKE_CURRENT_LIST_DIR}/RimPropertyFilterCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipsePropertyFilterCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimCellRangeFilter.h
${CMAKE_CURRENT_LIST_DIR}/RimCellRangeFilterCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimRegularLegendConfig.h
${CMAKE_CURRENT_LIST_DIR}/RimOilField.h
${CMAKE_CURRENT_LIST_DIR}/RimProject.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseCase.h
${CMAKE_CURRENT_LIST_DIR}/RimIdenticalGridCaseGroup.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseInputProperty.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseInputPropertyCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseInputCase.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseResultCase.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseView.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseResultDefinition.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseCellColors.h
${CMAKE_CURRENT_LIST_DIR}/RimCellEdgeColors.h
${CMAKE_CURRENT_LIST_DIR}/RimSimWellInView.h
${CMAKE_CURRENT_LIST_DIR}/RimSimWellInViewCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimWellPath.h
${CMAKE_CURRENT_LIST_DIR}/RimFileWellPath.h
${CMAKE_CURRENT_LIST_DIR}/RimModeledWellPath.h
${CMAKE_CURRENT_LIST_DIR}/RimWellPathGeometryDef.h
${CMAKE_CURRENT_LIST_DIR}/RimWellPathCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimWellPathTarget.h
${CMAKE_CURRENT_LIST_DIR}/RimScriptCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseStatisticsCase.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseStatisticsCaseCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimCalcScript.h
${CMAKE_CURRENT_LIST_DIR}/RimExportInputPropertySettings.h
${CMAKE_CURRENT_LIST_DIR}/RimBinaryExportSettings.h
${CMAKE_CURRENT_LIST_DIR}/Rim3dOverlayInfoConfig.h
${CMAKE_CURRENT_LIST_DIR}/RimTensorResults.h
${CMAKE_CURRENT_LIST_DIR}/RimReservoirCellResultsStorage.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseStatisticsCaseEvaluator.h
${CMAKE_CURRENT_LIST_DIR}/RimMimeData.h
${CMAKE_CURRENT_LIST_DIR}/RimCommandObject.h
${CMAKE_CURRENT_LIST_DIR}/RimTools.h
${CMAKE_CURRENT_LIST_DIR}/RimFaultInView.h
${CMAKE_CURRENT_LIST_DIR}/RimFaultInViewCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimFormationNames.h
${CMAKE_CURRENT_LIST_DIR}/RimFormationNamesCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimMockModelSettings.h
${CMAKE_CURRENT_LIST_DIR}/RimTernaryLegendConfig.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseFaultColors.h
${CMAKE_CURRENT_LIST_DIR}/RimNoCommonAreaNNC.h
${CMAKE_CURRENT_LIST_DIR}/RimNoCommonAreaNncCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechModels.h
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechCase.h
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechView.h
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechPropertyFilter.h
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechPropertyFilterCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechResultDefinition.h
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechCellColors.h
${CMAKE_CURRENT_LIST_DIR}/RimViewWindow.h
${CMAKE_CURRENT_LIST_DIR}/Rim3dView.h
${CMAKE_CURRENT_LIST_DIR}/RimGridView.h
${CMAKE_CURRENT_LIST_DIR}/Rim2dIntersectionView.h
${CMAKE_CURRENT_LIST_DIR}/Rim2dIntersectionViewCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimViewManipulator.h
${CMAKE_CURRENT_LIST_DIR}/RimCase.h
${CMAKE_CURRENT_LIST_DIR}/RimViewController.h
${CMAKE_CURRENT_LIST_DIR}/RimMainPlotCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimWellLogPlotCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimRftPlotCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimPltPlotCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimWellLogPlot.h
${CMAKE_CURRENT_LIST_DIR}/RimWellLogTrack.h
${CMAKE_CURRENT_LIST_DIR}/RimWellLogCurve.h
${CMAKE_CURRENT_LIST_DIR}/RimViewLinker.h
${CMAKE_CURRENT_LIST_DIR}/RimViewLinkerCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimWellLogExtractionCurve.h
${CMAKE_CURRENT_LIST_DIR}/RimWellLogFile.h
${CMAKE_CURRENT_LIST_DIR}/RimWellLogFileChannel.h
${CMAKE_CURRENT_LIST_DIR}/RimWellLogFileCurve.h
${CMAKE_CURRENT_LIST_DIR}/RimWellLogRftCurve.h
${CMAKE_CURRENT_LIST_DIR}/RimIntersection.h
${CMAKE_CURRENT_LIST_DIR}/RimIntersectionCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimContextCommandBuilder.h
${CMAKE_CURRENT_LIST_DIR}/RimGridCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimPlotCurve.h
${CMAKE_CURRENT_LIST_DIR}/RimIntersectionBox.h
${CMAKE_CURRENT_LIST_DIR}/RimMultiSnapshotDefinition.h
${CMAKE_CURRENT_LIST_DIR}/RimMdiWindowController.h
${CMAKE_CURRENT_LIST_DIR}/RimPropertyFilter.h
${CMAKE_CURRENT_LIST_DIR}/RimNamedObject.h
${CMAKE_CURRENT_LIST_DIR}/RimCheckableNamedObject.h
${CMAKE_CURRENT_LIST_DIR}/RimCheckableObject.h
${CMAKE_CURRENT_LIST_DIR}/RimGridTimeHistoryCurve.h
${CMAKE_CURRENT_LIST_DIR}/RimGeometrySelectionItem.h
${CMAKE_CURRENT_LIST_DIR}/RimEclipseGeometrySelectionItem.h
${CMAKE_CURRENT_LIST_DIR}/RimDialogData.h
${CMAKE_CURRENT_LIST_DIR}/RimTimeStepFilter.h
${CMAKE_CURRENT_LIST_DIR}/RimSummaryCalculation.h
${CMAKE_CURRENT_LIST_DIR}/RimSummaryCalculationCollection.h
${CMAKE_CURRENT_LIST_DIR}/RimSummaryCalculationVariable.h
${CMAKE_CURRENT_LIST_DIR}/RimStimPlanLegendConfig.h
${CMAKE_CURRENT_LIST_DIR}/RimStimPlanColors.h
${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogCurve.h
${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogFileCurve.h
${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogExtractionCurve.h
${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogRftCurve.h
${CMAKE_CURRENT_LIST_DIR}/RimVirtualPerforationResults.h
${CMAKE_CURRENT_LIST_DIR}/RimLegendConfig.h
${CMAKE_CURRENT_LIST_DIR}/RimWellLogCurveNameConfig.h
)


set (SOURCE_GROUP_SOURCE_FILES
${CMAKE_CURRENT_LIST_DIR}/RimEclipseCaseCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimCaseCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimCellFilter.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipsePropertyFilter.cpp
${CMAKE_CURRENT_LIST_DIR}/RimPropertyFilterCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipsePropertyFilterCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimCellRangeFilter.cpp
${CMAKE_CURRENT_LIST_DIR}/RimCellRangeFilterCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimRegularLegendConfig.cpp
${CMAKE_CURRENT_LIST_DIR}/RimOilField.cpp
${CMAKE_CURRENT_LIST_DIR}/RimProject.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseCase.cpp
${CMAKE_CURRENT_LIST_DIR}/RimIdenticalGridCaseGroup.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseInputProperty.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseInputPropertyCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseInputCase.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseResultCase.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseView.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseResultDefinition.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseCellColors.cpp
${CMAKE_CURRENT_LIST_DIR}/RimCellEdgeColors.cpp
${CMAKE_CURRENT_LIST_DIR}/RimSimWellInView.cpp
${CMAKE_CURRENT_LIST_DIR}/RimSimWellInViewCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellPath.cpp
${CMAKE_CURRENT_LIST_DIR}/RimFileWellPath.cpp
${CMAKE_CURRENT_LIST_DIR}/RimModeledWellPath.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellPathGeometryDef.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellPathCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellPathTarget.cpp
${CMAKE_CURRENT_LIST_DIR}/RimScriptCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseStatisticsCase.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseStatisticsCaseCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimCalcScript.cpp
${CMAKE_CURRENT_LIST_DIR}/RimExportInputPropertySettings.cpp
${CMAKE_CURRENT_LIST_DIR}/RimBinaryExportSettings.cpp
${CMAKE_CURRENT_LIST_DIR}/Rim3dOverlayInfoConfig.cpp
${CMAKE_CURRENT_LIST_DIR}/RimTensorResults.cpp
${CMAKE_CURRENT_LIST_DIR}/RimReservoirCellResultsStorage.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseStatisticsCaseEvaluator.cpp
${CMAKE_CURRENT_LIST_DIR}/RimMimeData.cpp
${CMAKE_CURRENT_LIST_DIR}/RimCommandObject.cpp
${CMAKE_CURRENT_LIST_DIR}/RimTools.cpp
${CMAKE_CURRENT_LIST_DIR}/RimFaultInView.cpp
${CMAKE_CURRENT_LIST_DIR}/RimFaultInViewCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimFormationNames.cpp
${CMAKE_CURRENT_LIST_DIR}/RimFormationNamesCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimMockModelSettings.cpp
${CMAKE_CURRENT_LIST_DIR}/RimTernaryLegendConfig.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseFaultColors.cpp
${CMAKE_CURRENT_LIST_DIR}/RimNoCommonAreaNNC.cpp
${CMAKE_CURRENT_LIST_DIR}/RimNoCommonAreaNncCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechModels.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechCase.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechView.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechPropertyFilter.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechPropertyFilterCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechResultDefinition.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGeoMechCellColors.cpp
${CMAKE_CURRENT_LIST_DIR}/RimViewWindow.cpp
${CMAKE_CURRENT_LIST_DIR}/Rim3dView.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGridView.cpp
${CMAKE_CURRENT_LIST_DIR}/Rim2dIntersectionView.cpp
${CMAKE_CURRENT_LIST_DIR}/Rim2dIntersectionViewCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimViewManipulator.cpp
${CMAKE_CURRENT_LIST_DIR}/RimCase.cpp
${CMAKE_CURRENT_LIST_DIR}/RimViewController.cpp
${CMAKE_CURRENT_LIST_DIR}/RimMainPlotCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellLogPlotCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimRftPlotCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimPltPlotCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellLogPlot.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellLogTrack.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellLogCurve.cpp
${CMAKE_CURRENT_LIST_DIR}/RimViewLinker.cpp
${CMAKE_CURRENT_LIST_DIR}/RimViewLinkerCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellLogExtractionCurve.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellLogFile.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellLogFileChannel.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellLogFileCurve.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellLogRftCurve.cpp
${CMAKE_CURRENT_LIST_DIR}/RimIntersection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimIntersectionCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimContextCommandBuilder.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGridCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimPlotCurve.cpp
${CMAKE_CURRENT_LIST_DIR}/RimIntersectionBox.cpp
${CMAKE_CURRENT_LIST_DIR}/RimMultiSnapshotDefinition.cpp
${CMAKE_CURRENT_LIST_DIR}/RimMdiWindowController.cpp
${CMAKE_CURRENT_LIST_DIR}/RimPropertyFilter.cpp
${CMAKE_CURRENT_LIST_DIR}/RimNamedObject.cpp
${CMAKE_CURRENT_LIST_DIR}/RimCheckableNamedObject.cpp
${CMAKE_CURRENT_LIST_DIR}/RimCheckableObject.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGridTimeHistoryCurve.cpp
${CMAKE_CURRENT_LIST_DIR}/RimGeometrySelectionItem.cpp
${CMAKE_CURRENT_LIST_DIR}/RimEclipseGeometrySelectionItem.cpp
${CMAKE_CURRENT_LIST_DIR}/RimDialogData.cpp
${CMAKE_CURRENT_LIST_DIR}/RimTimeStepFilter.cpp
${CMAKE_CURRENT_LIST_DIR}/RimSummaryCalculation.cpp
${CMAKE_CURRENT_LIST_DIR}/RimSummaryCalculationCollection.cpp
${CMAKE_CURRENT_LIST_DIR}/RimSummaryCalculationVariable.cpp
${CMAKE_CURRENT_LIST_DIR}/RimStimPlanLegendConfig.cpp
${CMAKE_CURRENT_LIST_DIR}/RimStimPlanColors.cpp
${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogCurve.cpp
${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogFileCurve.cpp
${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogExtractionCurve.cpp
${CMAKE_CURRENT_LIST_DIR}/Rim3dWellLogRftCurve.cpp
${CMAKE_CURRENT_LIST_DIR}/RimVirtualPerforationResults.cpp
${CMAKE_CURRENT_LIST_DIR}/RimLegendConfig.cpp
${CMAKE_CURRENT_LIST_DIR}/RimWellLogCurveNameConfig.cpp
)

list(APPEND CODE_HEADER_FILES
${SOURCE_GROUP_HEADER_FILES}
)

list(APPEND CODE_SOURCE_FILES
${SOURCE_GROUP_SOURCE_FILES}
)


source_group( "ProjectDataModel" FILES ${SOURCE_GROUP_HEADER_FILES} ${SOURCE_GROUP_SOURCE_FILES} ${CMAKE_CURRENT_LIST_DIR}/CMakeLists_files.cmake )
