/////////////////////////////////////////////////////////////////////////////////
//
//  Copyright (C) 2020 Equinor ASA
//
//  ResInsight is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ResInsight is distributed in the hope that it will be useful, but WITHOUT ANY
//  WARRANTY; without even the implied warranty of MERCHANTABILITY or
//  FITNESS FOR A PARTICULAR PURPOSE.
//
//  See the GNU General Public License at <http://www.gnu.org/licenses/gpl.html>
//  for more details.
//
/////////////////////////////////////////////////////////////////////////////////

#pragma once

#include "RimCustomObjectiveFunctionCollection.h"
#include "RimObjectiveFunction.h"

#include "cafPdmChildArrayField.h"
#include "cafPdmField.h"
#include "cafPdmObject.h"
#include "cafPdmProxyValueField.h"

#include <QString>

class RimCustomObjectiveFunctionWeight;
class RimEnsembleCurveSet;
class RimSummaryCase;

//==================================================================================================
///
//==================================================================================================
class RimCustomObjectiveFunction : public caf::PdmObject
{
    CAF_PDM_HEADER_INIT;

public:
    RimCustomObjectiveFunction();

    RimCustomObjectiveFunctionWeight*              addWeight();
    std::vector<RimCustomObjectiveFunctionWeight*> weights() const;
    std::vector<double>                            values() const;
    double                                         value( RimSummaryCase* summaryCase ) const;
    std::pair<double, double>                      minMaxValues() const;
    bool    weightContainsFunctionType( RimObjectiveFunction::FunctionType functionType ) const;
    QString title() const;
    QString autoGeneratedTitle() const;
    bool    isValid() const;
    void    onWeightChanged();
    void    invalidate();
    QString formulaString( std::vector<RifEclipseSummaryAddress> vectorSummaryAddresses ) const;

private:
    void defineUiTreeOrdering( caf::PdmUiTreeOrdering& uiTreeOrdering, QString uiConfigName /* = "" */ ) override;
    void defineEditorAttribute( const caf::PdmFieldHandle* field,
                                QString                    uiConfigName,
                                caf::PdmUiEditorAttribute* attribute ) override;

    RimEnsembleCurveSet*                  parentCurveSet() const;
    RimCustomObjectiveFunctionCollection* parentCollection() const;

    caf::PdmFieldHandle* userDescriptionField() override;

private:
    caf::PdmProxyValueField<QString>                           m_functionTitle;
    caf::PdmField<QString>                                     m_customFunctionTitle;
    caf::PdmChildArrayField<RimCustomObjectiveFunctionWeight*> m_weights;
    bool                                                       m_isValid;
};
