set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryEnsembleSumo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCaseSumo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSumoDataSource.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
