set(SOURCE_GROUP_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryEnsembleSumo.h
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCaseSumo.h
    ${CMAKE_CURRENT_LIST_DIR}/RimSummarySumoDataSource.h
)

set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryEnsembleSumo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummaryCaseSumo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimSummarySumoDataSource.cpp
)

list(APPEND CODE_HEADER_FILES ${SOURCE_GROUP_HEADER_FILES})
list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
