set(SOURCE_GROUP_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RifTextDataTableFormatter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseInputFileTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifRoffFileTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseOutputFileTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseRestartDataAccess.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseRestartFilesetAccess.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseSummaryTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseUnifiedRestartFileAccess.h
    ${CMAKE_CURRENT_LIST_DIR}/RifPerforationIntervalReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseInput.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseOutput.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseWell.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryReaderInterface.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseUserDataParserTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifColumnBasedUserDataParser.h
    ${CMAKE_CURRENT_LIST_DIR}/RifKeywordVectorParser.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderObservedData.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseSummary.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderRftInterface.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseRft.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderFmuRft.h
    ${CMAKE_CURRENT_LIST_DIR}/RifJsonEncodeDecode.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderInterface.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderMockModel.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseSummaryAddress.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseSummaryAddressQMetaType.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseRftAddress.h
    ${CMAKE_CURRENT_LIST_DIR}/RifWellPathImporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifHdf5ReaderInterface.h
    ${CMAKE_CURRENT_LIST_DIR}/RifColumnBasedUserData.h
    ${CMAKE_CURRENT_LIST_DIR}/RifKeywordVectorUserData.h
    ${CMAKE_CURRENT_LIST_DIR}/RifDataSourceForRftPlt.h
    ${CMAKE_CURRENT_LIST_DIR}/RifDataSourceForRftPltQMetaType.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseUserDataKeywordTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvUserData.h
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvUserDataParser.h
    ${CMAKE_CURRENT_LIST_DIR}/RifWellMeasurementReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifWellPathFormationReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifWellPathFormationsImporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifElementPropertyTableReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifElementPropertyReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanXmlReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifThermalFractureReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryCaseRestartSelector.h
    ${CMAKE_CURRENT_LIST_DIR}/RifCaseRealizationParametersReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifFileParseTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEnsembleStatisticsRft.h
    ${CMAKE_CURRENT_LIST_DIR}/RifActiveCellsReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvDataTableFormatter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseInputPropertyLoader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifInputPropertyLoader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSurfaceImporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifRoffReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifColorLegendData.h
    ${CMAKE_CURRENT_LIST_DIR}/RifElasticPropertiesReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelGeologicalFrkExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelDeviationFrkExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelPerfsFrkExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelAsymmetricFrkExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifThermalFractureTemplateSurfaceExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSurfaceExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifParameterXmlReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmCommonSummary.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEnsembleFractureStatisticsExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryReaderAggregator.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclEclipseSummary.h
    ${CMAKE_CURRENT_LIST_DIR}/RifWellIAFileWriter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseTextFileReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseKeywordContent.h
    ${CMAKE_CURRENT_LIST_DIR}/RifMultipleSummaryReaders.h
    ${CMAKE_CURRENT_LIST_DIR}/RifProjectSummaryDataWriter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderOpmRft.h
    ${CMAKE_CURRENT_LIST_DIR}/RifRftSegment.h
    ${CMAKE_CURRENT_LIST_DIR}/RifPressureDepthTextFileReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderPressureDepthData.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSeismicReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSeismicZGYReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifOpenVDSReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmRadialGridTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmFlowDeckFile.h
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvSummaryReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifRevealSummaryCsvReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifRevealCsvSectionSummaryReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanCsvSummaryReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderOpmCommon.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderOpmCommonActive.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseReportKeywords.h
    ${CMAKE_CURRENT_LIST_DIR}/RifInpExportTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEdfmTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifFaultReactivationModelExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifThermalToStimPlanFractureXmlOutput.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseSummaryAddressDefines.h
    ${CMAKE_CURRENT_LIST_DIR}/RifGridCalculation.h
    ${CMAKE_CURRENT_LIST_DIR}/RifGridCalculationImporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifGridCalculationExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryCalculation.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryCalculationImporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryCalculationExporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifPolygonReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifOsduWellPathReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifAsciiDataParseOptions.h
    ${CMAKE_CURRENT_LIST_DIR}/RifByteArrayArrowRandomAccessFile.h
    ${CMAKE_CURRENT_LIST_DIR}/RifArrowTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderRegularGridModel.h
    ${CMAKE_CURRENT_LIST_DIR}/RifVtkSurfaceImporter.h
    ${CMAKE_CURRENT_LIST_DIR}/RifSurfio.h
    ${CMAKE_CURRENT_LIST_DIR}/RifFileTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifVtkImportUtil.h
    ${CMAKE_CURRENT_LIST_DIR}/RifRmsWellPathReader.h
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmSummaryTools.h
    ${CMAKE_CURRENT_LIST_DIR}/RifEnsembleImportConfig.h
)

set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RifTextDataTableFormatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseInputFileTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRoffFileTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseOutputFileTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseRestartFilesetAccess.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseUnifiedRestartFileAccess.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseSummaryTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifPerforationIntervalReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseInput.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseOutput.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseWell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryReaderInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseUserDataParserTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifColumnBasedUserDataParser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifKeywordVectorParser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderObservedData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseSummary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderRftInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseRft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderFmuRft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifJsonEncodeDecode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderMockModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseSummaryAddress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseRftAddress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifWellPathImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifHdf5ReaderInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifColumnBasedUserData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifKeywordVectorUserData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifDataSourceForRftPlt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseUserDataKeywordTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvUserData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvUserDataParser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifWellMeasurementReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifWellPathFormationReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifWellPathFormationsImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifElementPropertyTableReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifElementPropertyReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanXmlReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifThermalFractureReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryCaseRestartSelector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifCaseRealizationParametersReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifFileParseTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifActiveCellsReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvDataTableFormatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEnsembleStatisticsRft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseInputPropertyLoader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifInputPropertyLoader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSurfaceImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRoffReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifColorLegendData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifElasticPropertiesReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelGeologicalFrkExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelDeviationFrkExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelPerfsFrkExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelAsymmetricFrkExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifThermalFractureTemplateSurfaceExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSurfaceExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifParameterXmlReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmCommonSummary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmFlowDeckFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEnsembleFractureStatisticsExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryReaderAggregator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclEclipseSummary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifWellIAFileWriter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseTextFileReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifMultipleSummaryReaders.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifProjectSummaryDataWriter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderOpmRft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRftSegment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifPressureDepthTextFileReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderPressureDepthData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSeismicReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSeismicZGYReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOpenVDSReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmRadialGridTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvSummaryReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRevealCsvSummaryReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseReportKeywords.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRevealCsvSectionSummaryReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanCsvSummaryReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderOpmCommon.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderOpmCommonActive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifInpExportTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEdfmTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifFaultReactivationModelExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifThermalToStimPlanFractureXmlOutput.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseSummaryAddressDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifGridCalculationImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifGridCalculationExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryCalculationImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryCalculationExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifPolygonReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOsduWellPathReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOsduWellLogReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifByteArrayArrowRandomAccessFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifArrowTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderRegularGridModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifVtkSurfaceImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSurfio.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifFileTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifVtkImportUtil.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRmsWellPathReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmSummaryTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEnsembleImportConfig.cpp
)

list(APPEND CODE_HEADER_FILES ${SOURCE_GROUP_HEADER_FILES})
list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
