set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RifTextDataTableFormatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseInputFileTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRoffFileTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseOutputFileTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseRestartFilesetAccess.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseUnifiedRestartFileAccess.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseSummaryTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifPerforationIntervalReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseInput.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseOutput.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseWell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryReaderInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseUserDataParserTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifColumnBasedUserDataParser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifKeywordVectorParser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderObservedData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEclipseSummary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderRftInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderFmuRft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifJsonEncodeDecode.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderMockModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseSummaryAddress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseRftAddress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifWellPathImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifHdf5ReaderInterface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifColumnBasedUserData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifKeywordVectorUserData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifDataSourceForRftPlt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseUserDataKeywordTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvUserData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvUserDataParser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifWellMeasurementReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifWellPathFormationReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifWellPathFormationsImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifElementPropertyTableReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifElementPropertyReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanXmlReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifThermalFractureReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryCaseRestartSelector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifCaseRealizationParametersReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifFileParseTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifActiveCellsReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvDataTableFormatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderEnsembleStatisticsRft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseInputPropertyLoader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifInputPropertyLoader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSurfaceImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRoffReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRoffWriter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifFormationNamesReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifElasticPropertiesReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelGeologicalFrkExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelDeviationFrkExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelPerfsFrkExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanModelAsymmetricFrkExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifThermalFractureTemplateSurfaceExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSurfaceExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifParameterXmlReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmCommonSummary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmFlowDeckFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmDeckTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEventKeywordFormatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEnsembleFractureStatisticsExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryReaderAggregator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclEclipseSummary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifWellIAFileWriter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseTextFileReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifMultipleSummaryReaders.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifProjectSummaryDataWriter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderOpmRft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRftSegment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifPressureDepthTextFileReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderPressureDepthData.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSeismicReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSeismicZGYReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmRadialGridTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifCsvSummaryReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRevealCsvSummaryReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseReportKeywords.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRevealCsvSectionSummaryReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifStimPlanCsvSummaryReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderOpmCommon.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderOpmCommonActive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifInpExportTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEdfmTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifFaultReactivationModelExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifThermalToStimPlanFractureXmlOutput.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEclipseSummaryAddressDefines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifGridCalculationImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifGridCalculationExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryCalculationImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSummaryCalculationExporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifPolygonReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOsduWellPathReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOsduWellLogReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifByteArrayArrowRandomAccessFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifArrowTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifReaderRegularGridModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifVfpInjTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifVfpProdTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifVtkSurfaceImporter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifSurfio.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifFileTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifVtkImportUtil.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifRmsWellPathReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifOpmSummaryTools.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RifEnsembleImportConfig.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
