set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotCellFilter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotCellFilterCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimPlotCellPropertyFilter.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
