name: Broken link check
on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: celinekurpershoek/link-checker@v1.0.1
      with:
        # Required:
        url: 'https://resinsight.org/'
        # optional:
        honorRobotExclusions: false
        ignorePatterns: ''
        recursiveLinks: false # Check all URLs on all reachable pages (could take a while)
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"
