set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileSet.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileSetCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileSetTools.cpp
)

list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
