set(SOURCE_GROUP_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileSet.h
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileSetCollection.h
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileSetTools.h
)

set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileSet.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileSetCollection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileSetTools.cpp
)

list(APPEND CODE_HEADER_FILES ${SOURCE_GROUP_HEADER_FILES})
list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
